services:
    postgres:
        container_name: dubmasterdb-container
        image: postgres
        environment:
          POSTGRES_DB: dubmasterdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5
        volumes:
          - postgres_dbmaster:/var/lib/postgres/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_dbmaster:
